# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(max_length=30, null=True, verbose_name='Название:'),
        ),
    ]
