# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0002_auto_20180630_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма:')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='Название:')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
        ),
    ]
