# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0004_changebalance_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='changebalance',
            name='category',
            field=models.CharField(max_length=30, null=True, verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='changebalance',
            name='change',
            field=models.CharField(choices=[('Spending', 'Расход'), ('Income', 'Поступление')], default='Income', max_length=8),
        ),
    ]
