# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0005_auto_20180630_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='changebalance',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Planning.Period'),
        ),
    ]
