# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0006_changebalance_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changebalance',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Planning.Period'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='period',
            name='end_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Укажите конец периода:'),
        ),
        migrations.AlterField(
            model_name='period',
            name='name',
            field=models.CharField(help_text='Например: название месяца, номер  и т.п.', max_length=30, null=True, verbose_name='Название:'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Укажите начало периода:'),
        ),
    ]
