# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-30 22:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0007_auto_20180630_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='end_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Конец периода:'),
        ),
        migrations.AlterField(
            model_name='period',
            name='start_Date',
            field=models.DateField(default=datetime.date.today, verbose_name='Начало периода:'),
        ),
    ]
