# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 18:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0008_auto_20180630_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changebalance',
            name='date',
        ),
        migrations.RemoveField(
            model_name='changebalance',
            name='period',
        ),
    ]
