# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0010_auto_20180707_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentbalance',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Текущий баланс'),
        ),
    ]
