# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Planning', '0013_auto_20180708_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changebalance',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='Категория:'),
        ),
        migrations.AlterField(
            model_name='changebalance',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название:'),
        ),
    ]
